name: My CI Regression 

on:
  push:
    branches:
      - main

jobs:
  CI-Rafael-Regression:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: instalar Node
        uses: actions/setup-node@v4
        with: 
          node-version: 18
      
      - name: Instalar dependencias
        run: npm i

      - name: Correr Regresion
        uses: cypress-io/github-action@v6
        with:
          browser: chrome

      - name: Slack Notification
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: Rafa Test
          SLACK_MESSAGE: Regression Test
          SLACK_COLOR: ${{ job.status }}