name: My CI Sanity

on:
  push:
    branches-ignore:
      - main

jobs:
  CI-Rafael-Sanity:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: instalar Node
        uses: actions/setup-node@v4
        with: 
          node-version: 18
      
      - name: Instalar dependencias
        run: npm i

      - name: Run Test 
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          headed: true
          # En el Spec cambiar la ruta del test a ejecutar
          spec: cypress/e2e/trello/GX2-10188-moverYArchivar.cy.js
          
      - name: Slack Notification
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: Rafa Test
          SLACK_MESSAGE: Sanity Test
          SLACK_COLOR: ${{ job.status }}

        